package com.ramo.iFootballFixtures.Enums;

public enum MatchStatus {
    SCHEDULED,
    LIVE,
    POSTPONED,
    CANCELED,
    FIRST_HALF,
    HALF_TIME,
    SECOND_HALF,
    EXTRA_TIME_FIRST_HALF,
    EXTRA_TIME_HALF_TIME,
    EXTRA_TIME_SECOND_HALF,
    PENALTY_SHOOTOUT,
    FULL_TIME,
    EXTRA_TIME_FINISHED,
    PENALTY_SHOOTOUT_FINISHED,
    ABANDONED,
    SUSPENDED
}

